version: '3.9'
services:
  db:
    image: mysql:8
    environment:
      MYSQL_DATABASE: students
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: app
      MYSQL_PASSWORD: app
    ports:
      - '3306:3306'
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - dbdata:/var/lib/mysql
volumes:
  dbdata:
